#!/bin/sh

ramrootfs_enabled() {
	return 0
}

ramrootfs_run() {
	if [ -n "$ROOTFS_DIR" ]; then
		mkdir "$ROOTFS_DIR.org"
		mount --move "$ROOTFS_DIR" "$ROOTFS_DIR.org"
		size="$(grep MemTotal /proc/meminfo | awk '{print $2}')"
		size="$((size/100*90))"
		zram_dev="$(zramctl -f -s "${size}KiB")"
		mkfs.ext4 -O ^has_journal "$zram_dev"
		mount -o discard "$zram_dev" "$ROOTFS_DIR"
		cp -a "$ROOTFS_DIR.org/." "$ROOTFS_DIR"

		# Needed for https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html
		# https://github.com/systemd/systemd/pull/20578
		mount -t tmpfs tmpfs "$ROOTFS_DIR/run"
		mkdir "$ROOTFS_DIR/run/systemd"
		org_root_dev="$(awk "\$2==\"$ROOTFS_DIR.org\" {print \$1}" /proc/mounts)"
		org_root_dev="$(realpath "$org_root_dev")"
		org_root_dev="${org_root_dev#/dev/}"
		slave="$(ls -1 /sys/block/$org_root_dev/slaves | head -n 1)"
		if [ -n "$slave" ]; then
			org_root_dev="$slave"
		fi
		major_minor="$(cat /sys/class/block/$org_root_dev/dev)"
		ln -sf "/dev/block/$major_minor" "$ROOTFS_DIR/run/systemd/volatile-root"

		umount "$ROOTFS_DIR.org"
	fi
}
