LICENSE = "MIT"
DESCRIPTION = "A Test image build on the mukube minimal image"

require mukube-image.bb

# Parameters passed directly to qemu and runqemu
TEST_QEMUPARAMS = "-m 20000 -smp 4"
TEST_RUNQEMUPARAMS = "wic ovmf kvm"

IMAGE_FEATURES += "\
    debug-tweaks \
    allow-empty-password \
    empty-root-password \
    ssh-server-dropbear \
    "

IMAGE_INSTALL += "k8s-testing"

# Pass IP configuration on kernel commandline
APPEND += " ip=192.168.7.2::192.168.7.1:255.255.255.0"

# Emtpy config.ext4 file generated by the k8s-testing recipe
# TODO: This hardcoded path is not ideal
MK_CONFIG_FILE_PATH = "${BASE_WORKDIR}/core2-64-poky-linux/k8s-testing/1.0-r0/temp/config.ext4"
#TESTIMAGE_AUTO = "1"
