LICENSE = "MIT"
DESCRIPTION = "A development image build on the mukube image"

require recipes-mukube/images/mukube-image.bb

IMAGE_FEATURES += "\
    debug-tweaks \
    allow-empty-password \
    empty-root-password \
    "

IMAGE_INSTALL += "k8s-testing"

# test_config.ext4 partition generated by the k8s-testing recipe
MUKUBE_CONFIG_PARTITION = "${DEPLOY_DIR_IMAGE}/test_config.ext4"
